### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by cesar-lizurey** [BenHayak/SOME_Targeting_Tool#1]
Hello,
Do you plan on a Firefox version?
Thanks for your work, very useful!

**Comment by BenHayak** [comment]
That’s not a bad idea, might take a few weeks to find the right time, but I
will look into it!

**Comment by cesar-lizurey** [comment]
I can help, if you want. I don't know if you'll transform this repo into a monorepo or if you'll create another one, but I've written a few Firefox plugins, I could give you a hand :)

**Comment by BenHayak** [comment]
Thanks I appreciate it!
The JavaScript code I wrote should work in any browser, l will take a look
and If it requires anything more than that I count on using your Firefox
experience 🤘

**Comment by cesar-lizurey** [comment]
Thanks a lot :)

**Comment by BenHayak** [comment]
It was very simple process. 

There:
https://addons.mozilla.org/en-US/firefox/addon/same-origin-method-execution/

I have only done basic testing though, if you'd like, feel free to test and report back in case you find any bugs & post a review. 

Thanks for the idea!

**Comment by BenHayak** [comment]
https://github.com/BenHayak/Firefox_Extension_SOME

**Comment by cesar-lizurey** [comment]
Wow, that was fast!
Thanks a lot.
